### ISSUE TITLE
can u release the newest version?

### ISSUE THREAD

**Issue by myworldbox** [VivaanKumar/react-multiplayer-chess#1]
the ui of repo is different to your showcase link.

**Comment by VivaanKumar** [comment]
Hey so this repo is the code of my old react chess website, the new chess website link that I have made is a different repo

**Comment by VivaanKumar** [comment]
Here is the link: https://github.com/VivaanKumar/erth :)

**Comment by myworldbox** [comment]
thx this is great repo
